### PR TITLE
gitignore added

### PR DESCRIPTION
**Pull request by blueberry1312**
Added test.md to the ignore list on .gitignore file.
Added Key features and Future features on README.md

### CODE REVIEW

**Review by ghost — CHANGES_REQUESTED** [review]
Hi @blueberry1312  

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!




## Highlights


## Required Changes ♻️

- [x] Kindly try as much as possible to make your Pull Request description as descriptive as possible. You can describe what you did in this milestone in detail. Kindly  check this [link](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/documentation/articles/professional_repo_rules.md) for more info
- [x]  I also noticed that your readme file is missing some important headers like the `Key features` and `future features`. Kindly be sure to add them to make your readme more proffessional

## Optional suggestions

N/A
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by blueberry1312** [comment]
hi @frank1738 !,
I understand the second change ( add key features and future features) I only removed them because I thought they weren't necessary for this project, I'll add them back.
About the first change, I don't understand exactly where I should make the change, or is it a suggestion for future commits and pulls?
And finally, about optional suggestions _"Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise."_ Do you mean that I can modify the readme in this same pull request so as not to generate another one or not? Could you guide me a little more with that please, thanks!!.
Cheers!

**Comment by ghost** [comment]
> hi @frank1738 !, I understand the second change ( add key features and future features) I only removed them because I thought they weren't necessary for this project, I'll add them back. About the first change, I don't understand exactly where I should make the change, or is it a suggestion for future commits and pulls? And finally, about optional suggestions _"Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise."_ Do you mean that I can modify the readme in this same pull request so as not to generate another one or not? Could you guide me a little more with that please, thanks!!. Cheers!

Hello @blueberry1312. About the first suggestion, you can edit your pull request description and make it more descriptive as shown below.

- [ ] Click on the three-dotted button

image

- [ ] Then you will see the edit option

image

- [ ] Finally, all changes are made under one Pull Request, so you don't create another pull after making the changes. Just push the changes to the current branch you are working on

**Comment by blueberry1312** [comment]
Thanks @frank1738 !, apparently I was a bit confused, every time I commit, I pull request, I didn't realize that I could do many commits and pushes in the same pull request, I'll proceed to make the changes then, thank you very much!!

**Comment by blueberry1312** [comment]
@frank1738 another question, i update readme with key and future features, but actually de project is only a hello world html file so i dont know what put in. Also about the edit of the description, you just need me to edit correctly the description of the photo you sent me?, or a general review of my other pull/merges?
211863366-4d803202-e366-416d-b442-bc8dfa006fb9

**Review by iambenkis — APPROVED** [review]
### Hi  @blueberry1312     , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 


cr-approve

## Highlights

GitHub review feature :heavy_check_mark:
Good commit messages. :heavy_check_mark: 
Good renaming the branch nam:heavy_check_mark:  

## Optional 

**_Every comment with the [**OPTIONAL**] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._**

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me `@iambenkis` in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
